source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim

set backup
set backupdir=C:\\Temp
set undodir=C:\\Temp
set directory=C:\\Temp
set undodir=C:\\Temp
set writebackup
set dir=$TEMP
colorscheme torte
" Force four space tabs
set tabstop=4
set shiftwidth=4
set expandtab
" put into _gvimrc?
set guifont=Noto_Mono_for_Powerline:h9:cANSI:qDRAFT

